# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Text2SQL',
                'doc_host': 'https://tripathysagar.github.io',
                'git_url': 'https://github.com/tripathysagar/Text2SQL',
                'lib_path': 'Text2SQL'},
  'syms': { 'Text2SQL.SnowflakeCore': { 'Text2SQL.SnowflakeCore.ParentSchema': ( 'snowflakecore.html#parentschema',
                                                                                 'Text2SQL/SnowflakeCore.py'),
                                        'Text2SQL.SnowflakeCore.QueryResult': ( 'snowflakecore.html#queryresult',
                                                                                'Text2SQL/SnowflakeCore.py'),
                                        'Text2SQL.SnowflakeCore.TableAttr': ('snowflakecore.html#tableattr', 'Text2SQL/SnowflakeCore.py'),
                                        'Text2SQL.SnowflakeCore.execute_query': ( 'snowflakecore.html#execute_query',
                                                                                  'Text2SQL/SnowflakeCore.py'),
                                        'Text2SQL.SnowflakeCore.get_fk': ('snowflakecore.html#get_fk', 'Text2SQL/SnowflakeCore.py'),
                                        'Text2SQL.SnowflakeCore.get_schema_context': ( 'snowflakecore.html#get_schema_context',
                                                                                       'Text2SQL/SnowflakeCore.py')}}}
